version: "3"

services:
  timescaledb:
    image: "timescale/timescaledb:latest-pg12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=wakaexporter

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - 3000:3000
