name: Build and Deploy to my k8s cluster.

on:
  push:
    branches:
      - master

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: j2gg0s/wakaexporter:${{ steps.date.outputs.date }}.${{ github.sha }}

    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
